CREATE TABLE public.users (
	user_name text NULL,
	"role" text NULL,
	mobile_number text NULL,
	opening_balance text NULL,
	"permission" jsonb NULL,
	"password" text NULL
);

ALTER TABLE public.users ADD id bigint not NULL GENERATED BY DEFAULT AS IDENTITY;
