CREATE TABLE public.users (
	user_name text NULL,
	"role" text NULL,
	mobile_number text NULL,
	opening_balance text NULL,
	"permission" jsonb NULL,
	"password" text NULL
);

ALTER TABLE public.users ADD id bigint not NULL GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE public.customers (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	company text NULL,
	first_name text NULL,
	address text NULL,
	email text NULL,
	mobile_no text NULL,
	due_limit text NULL,
	balance text NULL,
	other text NULL,
	tier text NULL
);
