CREATE TABLE public.users (
	username text NULL,
	"role" text NULL,
	mobilenumber text NULL,
	openingbalance text NULL,
	"permission" jsonb NULL,
	"password" text NULL
);

ALTER TABLE public.users ADD id bigint not NULL GENERATED BY DEFAULT AS IDENTITY;
